apiVersion: apps/v1
kind: Deployment
metadata:
  name: elizsa-pod
  labels:
    app: gpt-neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-neo
  template:
    metadata:
      labels:
        app: gpt-neo
    spec:
      containers:
      - name: gpt-neo
        image: ghcr.io/huggingface/text-generation-inference:latest  # ✅ Fixed Image
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "16Gi"
            cpu: "8"
            nvidia.com/gpu: 1
          requests:
            memory: "8Gi"
            cpu: "4"
        env:
        - name: MODEL_NAME
          value: "EleutherAI/gpt-neo-1.3B"
        - name: MAX_LENGTH
          value: "100"
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-neo
spec:
  selector:
    app: gpt-neo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

  